/** Pino redact paths. Never log credentials, tokens, or customer phones. */
export const LOG_REDACT_PATHS = [
  'req.headers.authorization',
  'req.headers.cookie',
  'req.headers["x-api-key"]',
  'password',
  'passwordHash',
  '*.password',
  '*.passwordHash',
  'phoneNumber',
  '*.phoneNumber',
  'DATABASE_URL',
  '*.DATABASE_URL',
  'JWT_SECRET',
  'accessToken',
  '*.accessToken',
  'PLATFORM_ADMIN_PASSWORD',
  '*.PLATFORM_ADMIN_PASSWORD',
  'BALE_SAFIR_API_ACCESS_KEY',
  '*.BALE_SAFIR_API_ACCESS_KEY',
  'api-access-key',
  '*.api-access-key',
  'req.headers["api-access-key"]',
] as const;
